/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.ide;


/**
 * Use this class to register ide components.
 */
public class OtherDslIdeModule extends AbstractOtherDslIdeModule {
}
