/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl4test.OtherDslRuntimeModule;
import org.xtext.example.mydsl4test.OtherDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OtherDslIdeSetup extends OtherDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OtherDslRuntimeModule(), new OtherDslIdeModule()));
	}
	
}
