/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test;

import org.eclipse.emf.ecore.EPackage;
import org.xtext.example.mydsl3test.MyDslTestStandaloneSetup;
import org.xtext.example.mydsl3test.myDslTest.MyDslTestPackage;
import org.xtext.example.mydsl4test.otherDsl.OtherDslPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OtherDslStandaloneSetup extends OtherDslStandaloneSetupGenerated {

	public static void doSetup() {
		MyDslTestStandaloneSetup.doSetup();
		new OtherDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey(OtherDslPackage.eNS_URI)) {
			EPackage.Registry.INSTANCE.put(OtherDslPackage.eNS_URI, OtherDslPackage.eINSTANCE);
		}
		super.register(injector);
	}
}
