/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl4test.parser.antlr.internal.InternalOtherDslParser;
import org.xtext.example.mydsl4test.services.OtherDslGrammarAccess;

public class OtherDslParser extends AbstractAntlrParser {

	@Inject
	private OtherDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOtherDslParser createParser(XtextTokenStream stream) {
		return new InternalOtherDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "OtherRoot";
	}

	public OtherDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OtherDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
