/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.otherDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl4test.otherDsl.OtherDslPackage
 * @generated
 */
public interface OtherDslFactory extends EFactory
{
	/**
	 * The singleton instance of the factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	OtherDslFactory eINSTANCE = org.xtext.example.mydsl4test.otherDsl.impl.OtherDslFactoryImpl.init();

	/**
	 * Returns a new object of class '<em>Other Root</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Other Root</em>'.
	 * @generated
	 */
	OtherRoot createOtherRoot();

	/**
	 * Returns the package supported by this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the package supported by this factory.
	 * @generated
	 */
	OtherDslPackage getOtherDslPackage();

} //OtherDslFactory
