/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.otherDsl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl4test.otherDsl.OtherDslFactory
 * @model kind="package"
 * @generated
 */
public interface OtherDslPackage extends EPackage
{
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "otherDsl";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://www.xtext.org/example/mydsl4test/OtherDsl";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "otherDsl";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	OtherDslPackage eINSTANCE = org.xtext.example.mydsl4test.otherDsl.impl.OtherDslPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4test.otherDsl.impl.OtherRootImpl <em>Other Root</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4test.otherDsl.impl.OtherRootImpl
	 * @see org.xtext.example.mydsl4test.otherDsl.impl.OtherDslPackageImpl#getOtherRoot()
	 * @generated
	 */
	int OTHER_ROOT = 0;

	/**
	 * The feature id for the '<em><b>Value</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OTHER_ROOT__VALUE = 0;

	/**
	 * The number of structural features of the '<em>Other Root</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OTHER_ROOT_FEATURE_COUNT = 1;


	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4test.otherDsl.OtherRoot <em>Other Root</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Other Root</em>'.
	 * @see org.xtext.example.mydsl4test.otherDsl.OtherRoot
	 * @generated
	 */
	EClass getOtherRoot();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4test.otherDsl.OtherRoot#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Value</em>'.
	 * @see org.xtext.example.mydsl4test.otherDsl.OtherRoot#getValue()
	 * @see #getOtherRoot()
	 * @generated
	 */
	EReference getOtherRoot_Value();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	OtherDslFactory getOtherDslFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals
	{
		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4test.otherDsl.impl.OtherRootImpl <em>Other Root</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4test.otherDsl.impl.OtherRootImpl
		 * @see org.xtext.example.mydsl4test.otherDsl.impl.OtherDslPackageImpl#getOtherRoot()
		 * @generated
		 */
		EClass OTHER_ROOT = eINSTANCE.getOtherRoot();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference OTHER_ROOT__VALUE = eINSTANCE.getOtherRoot_Value();

	}

} //OtherDslPackage
