/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl3test.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl3test.MyDslTestRuntimeModule;
import org.xtext.example.mydsl3test.MyDslTestStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDslTestIdeSetup extends MyDslTestStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDslTestRuntimeModule(), new MyDslTestIdeModule()));
	}
	
}
