/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl3test.ide;


/**
 * Use this class to register ide components.
 */
public class MyDslTestIdeModule extends AbstractMyDslTestIdeModule {
}
