/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl3test.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl3test.parser.antlr.internal.InternalMyDslTestParser;
import org.xtext.example.mydsl3test.services.MyDslTestGrammarAccess;

public class MyDslTestParser extends AbstractAntlrParser {

	@Inject
	private MyDslTestGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyDslTestParser createParser(XtextTokenStream stream) {
		return new InternalMyDslTestParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MyDslTestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslTestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
