/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.scoping;

import org.xtext.example.mydsl3test.scoping.MyDslTestScopeProvider;

public abstract class AbstractOtherDslScopeProvider extends MyDslTestScopeProvider {
}
