/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl3test;

import org.eclipse.emf.ecore.EPackage;
import org.xtext.example.mydsl3test.myDslTest.MyDslTestPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDslTestStandaloneSetup extends MyDslTestStandaloneSetupGenerated {

	public static void doSetup() {
		new MyDslTestStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey(MyDslTestPackage.eNS_URI)) {
			EPackage.Registry.INSTANCE.put(MyDslTestPackage.eNS_URI, MyDslTestPackage.eINSTANCE);
		}
		super.register(injector);
	}
}
