/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl3test;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslTestRuntimeModule extends AbstractMyDslTestRuntimeModule {
}
