/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.xtext.example.mydsl3test.validation.MyDslTestValidator;

public abstract class AbstractOtherDslValidator extends MyDslTestValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.xtext.org/example/mydsl4test/OtherDsl"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.xtext.org/example/mydsl3test/MyDslTest"));
		return result;
	}
}
