/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl3test.myDslTest.Greeting;
import org.xtext.example.mydsl3test.myDslTest.Model;
import org.xtext.example.mydsl3test.myDslTest.MyDslTestPackage;
import org.xtext.example.mydsl3test.serializer.MyDslTestSemanticSequencer;
import org.xtext.example.mydsl4test.otherDsl.OtherDslPackage;
import org.xtext.example.mydsl4test.otherDsl.OtherRoot;
import org.xtext.example.mydsl4test.services.OtherDslGrammarAccess;

@SuppressWarnings("all")
public class OtherDslSemanticSequencer extends MyDslTestSemanticSequencer {

	@Inject
	private OtherDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslTestPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslTestPackage.GREETING:
				sequence_Greeting(context, (Greeting) semanticObject); 
				return; 
			case MyDslTestPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			}
		else if (epackage == OtherDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case OtherDslPackage.OTHER_ROOT:
				sequence_OtherRoot(context, (OtherRoot) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     OtherRoot returns OtherRoot
	 *
	 * Constraint:
	 *     value=Model
	 */
	protected void sequence_OtherRoot(ISerializationContext context, OtherRoot semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, OtherDslPackage.Literals.OTHER_ROOT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, OtherDslPackage.Literals.OTHER_ROOT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOtherRootAccess().getValueModelParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
}
