/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl3test.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyDslTestUiModule extends AbstractMyDslTestUiModule {

	public MyDslTestUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
