/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl3test.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl3test.ui.internal.Mydsl3testActivator;

public class MyDslTestUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mydsl3testActivator.getInstance().getInjector("org.xtext.example.mydsl3test.MyDslTest");
	}

}
