/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.example.mydsl4test.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OtherDslUiModule extends AbstractOtherDslUiModule {

	public OtherDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
